on:
  workflow_dispatch:
  workflow_call:
    inputs:
    
      DOCKER_REGISTER:
        required: true
        type: string
  
jobs:
  Docker_Azure:
    runs-on: ubuntu-latest  
    steps:
    
      - name: Azure ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Build and Push ACR
        run: |
          docker build . -t ${{ secrets.ACR_SERVER }}/${{ secrets.REPOSITORIO }}:${{ github.run_number }}
          docker push ${{ secrets.ACR_SERVER }}/${{ secrets.REPOSITORIO }}:${{ github.run_number }}
