on:
  workflow_dispatch:
  workflow_call:

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: alejo-quind/calculator-front
          token: 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
          
      - name: Tree
        run: tree
        
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          arg: |
            sonar.exclusions= **/node_modules/**,**/*.test.js,**/alejo-helm/**
            sonar.testExecutionReportPaths=test-report.xml
            sonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: 'ad36fe2bf378c4b38436779c30f1c058a5cc74b5'
          SONAR_HOST_URL: 'https://sonarcloud.io'

      - name: Echo message
        run: echo "¡Funcionó!"
