on:
  workflow_dispatch:
  workflow_call:

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: alejo-quind/calculator-front
          token: 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
          
      - name: NPM
        run: | 
          npm install
          i -D jest-sonar-reporter
          npm run build
          npm run test
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: 'ad36fe2bf378c4b38436779c30f1c058a5cc74b5'
          SONAR_HOST_URL: 'https://sonarcloud.io'

      - name: Tree
        run: tree

      - name: Echo message
        run: echo "¡Funcionó!"
