on:
  workflow_dispatch:
  workflow_call:

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          repository: ${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
             
      - name: Show values.yaml
        run: cat alejo-helm/values.yaml
        
      - name: Replace tokens in values.yaml
        run: |
          envsubst < alejo-helm/values.yaml > alejo-helm/values.yaml
        env:
          POD_NAME: ${{ secrets.POD_NAME }}
          SVC_NAME: ${{ secrets.SVC_NAME }}
          APP: ${{ secrets.APP }}
          ACR_SERVER: ${{ secrets.ACR_SERVER }}
          REPOSITORIO: ${{ secrets.REPOSITORIO }}
          VER: ${{ secrets.VER }}
          TAG_ID: ${{ secrets.TAG_ID }}
          
      - name: Tree
        run: tree
          
      - name: Show values.yaml
        run: cat alejo-helm/values.yaml
  
      - name: NPM
        run: | 
          npm install
          npm install react-scripts@latest
          npm i -D jest-sonar-reporter
          npm run build
          npm run test
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        
      - name: Echo secret SONAR_TOKEN 
        run: echo ${{ secrets.SONAR_TOKEN }}
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'Drop'
          path: '${{ github.workspace }}/build'
          
      - name: Echo secret GITHUB_TOKEN 
        run: echo ${{ secrets.GITHUB_TOKEN }}
        
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://20.62.34.254:8080/calculator'
          cmd_options: '-J report_json'

      - name: Echo message
        run: echo "¡Funcionó!"
