on:
  workflow_dispatch:
  workflow_call:

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo message
        run: echo "¡Funcionó!"
      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: alejo-quind/calculator-front
          token: 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
 
