on:
  workflow_dispatch:
  workflow_call:

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          repository: ${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
                 
      - name: Replace tokens in values.yaml
        run: |
          envsubst < alejo-helm/values.yaml > alejo-helm/values.yaml
        env:
          POD_NAME: ${{ secrets.POD_NAME }}
          SVC_NAME: ${{ secrets.SVC_NAME }}
          APP: ${{ secrets.APP }}
          ACR_SERVER: ${{ secrets.ACR_SERVER }}
          REPOSITORIO: ${{ secrets.REPOSITORIO }}
          VER: ${{ secrets.VER }}
          TAG_ID: ${{ secrets.TAG_ID }}
  
      - name: NPM
        run: | 
          npm install
          npm install react-scripts@latest
          npm i -D jest-sonar-reporter
          npm run build
          npm run test
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'Drop'
          path: '${{ github.workspace }}/build'

      - name: Azure ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Build and Push ACR
        run: |
          docker build . -t ${{ secrets.ACR_SERVER }}/${{ secrets.REPOSITORIO }}:${{ github.sha }}
          docker push ${{ secrets.ACR_SERVER }}/${{ secrets.REPOSITORIO }}:${{ github.sha }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az login --service-principal -u c71b4899-08c0-4108-85cc-7ad926c0dc7e -p WG48Q~Q_BkxyBJttB7jjQdFZPHFgwhjsECzJnbwM --tenant f2567840-b2b7-49ad-8240-568a42281394
            az aks get-credentials --resource-group resource-group-alejandro-mena --name alejoaks
      
      - name: cat kube config
        run: cat .kube/config
            
      - name: Echo message
        run: echo "¡Funcionó!"
