on:
  workflow_dispatch:
  workflow_call:

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository: ${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN}}
          
      - name: NPM
        run: | 
          npm install
          npm install react-scripts@latest
          npm i -D jest-sonar-reporter
          npm run build
          npm run test
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: 'ad36fe2bf378c4b38436779c30f1c058a5cc74b5'
          SONAR_HOST_URL: 'https://sonarcloud.io'

      - name: Tree
        run: tree
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'Drop'
          path: '${{ github.workspace }}/build'

      - name: Echo message
        run: echo "¡Funcionó!"
