on:
  workflow_dispatch:
  workflow_call:

jobs:
  echo-message:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          repository: ${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          
      - name: Modificar variable en archivo de texto
        run: |
          tree
          sed -i 's/VAR: "valor a remplazar"/VAR: "nuevo valor"/g' archivo.txt
          cat ${{ github.workspace }}/archivo.txt
          
      - name: NPM
        run: | 
          npm install
          npm install react-scripts@latest
          npm i -D jest-sonar-reporter
          npm run build
          npm run test
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'Drop'
          path: '${{ github.workspace }}/build'

      - name: Azure ACR login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Build and Push ACR
        run: |
          docker build . -t ${{ secrets.ACR_SERVER }}/${{ secrets.REPOSITORIO }}:12345
          docker push ${{ secrets.ACR_SERVER }}/${{ secrets.REPOSITORIO }}:12345
          
      - name: Azure CLI install and credentials
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az login --service-principal -u c71b4899-08c0-4108-85cc-7ad926c0dc7e -p WG48Q~Q_BkxyBJttB7jjQdFZPHFgwhjsECzJnbwM --tenant f2567840-b2b7-49ad-8240-568a42281394
          az aks get-credentials --resource-group resource-group-alejandro-mena --name alejoaks
      
      - name: Cat kube config
        run: sudo cat /home/runner/.kube/config
      
      - name: Setup Helm  
        uses: azure/setup-helm@v3
        with:
           version: 'latest' # default is latest (stable)
           token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install
        
      - name: Helm deployment
        run: helm upgrade --namespace default --install --values alejo-helm/values.yaml ${{ secrets.APP }} alejo-helm
        
      - name: Echo message
        run: echo "¡Funcionó!"
