
on:
  workflow_dispatch:
  workflow_call:
    inputs:
    
      BUILD_ENV:
        required: true
        type: string

      KUBERNETES_WITH:
        required: true
        type: string

      TEST_WITH:
        required: true
        type: string
  
      DOCKER_REGISTER:
        required: true
        type: string
        
jobs:
          
  Project_Build_and_Test:
    uses: alejo-quind/pipeline-templates/.github/workflows/Project-Build-and-Test.yml@main 
    secrets:
      inherit
    with:
      TEST_WITH: ${{ inputs.TEST_WITH }}
      BUILD_ENV: ${{ inputs.BUILD_ENV }}

  Docker_Build_and_Push:
    uses: alejo-quind/pipeline-templates/.github/workflows/Docker-Build-and-Push.yml@main 
    needs: Project_Build_and_Test
    secrets:
      inherit
    with:
      DOCKER_REGISTER: ${{ inputs.DOCKER_REGISTER }}

  Kubernetes_Deployment:
    uses: alejo-quind/pipeline-templates/.github/workflows/Kubernetes-Deployment.yml@main 
    needs: Docker_Build_and_Push
    secrets:
      inherit
    with:
      KUBERNETES_WITH: ${{ inputs.KUBERNETES_WITH }}
      
