on:
  workflow_dispatch:
  workflow_call:
    inputs:
    
      REPO_NAME:
        required: true
        type: string
        
      REPO_TOKEN:
        required: true
        type: string
        
      POD_NAME:
        required: true
        type: string
  
      SVC_NAME:
        required: true
        type: string
        
      APP:
        required: true
        type: string

      ACR_SERVER:
        required: true
        type: string
        
      REPOSITORIO:
        required: true
        type: string

      SONAR_TOKEN:
        required: true
        type: string
        
      SONAR_HOST:
        required: true
        type: string
        
jobs:
  echo-message:
    runs-on: ubuntu-latest  
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          repository: ${{ inputs.REPO_NAME }}
          token: ${{ inputs.REPO_TOKEN }}
          
      - name: Replace token
        run: |
          sed -i "s/#{POD_NAME}#/${{ inputs.POD_NAME }}/g; s/#{SVC_NAME}#/${{ inputs.SVC_NAME }}/g; s/#{APP}#/${{ inputs.APP }}/g; s/#{ACR_SERVER}#/${{ inputs.ACR_SERVER }}/g; s/#{REPOSITORIO}#/${{ inputs.REPOSITORIO }}/g; s/#{TAG_ID}#/${{ github.run_number }}/g" ${{ github.workspace }}/alejo-helm/values.yaml
          cat ${{ github.workspace }}/alejo-helm/values.yaml
          
      - name: NPM
        run: | 
          npm install
          npm install react-scripts@latest
          npm i -D jest-sonar-reporter
          npm run build
          npm run test
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ inputs.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{ inputs.SONAR_HOST }}
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'Drop'
          path: '${{ github.workspace }}/build'
