on:
  workflow_dispatch:
  workflow_call:
    inputs:
    
      TEST_WITH:
        required: true
        type: string

      BUILD_ENV:
        required: true
        type: string
  
jobs:
  NPM:
    runs-on: ubuntu-latest  
    if: ${{ inputs.BUILD_ENV == 'npm' }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2.7.0
        with:
          repository: ${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}

      - name: Jest test
        if: ${{ inputs.TEST_WITH == 'jest' }}
        run: | 
          npm install
          npm install react-scripts@latest
          npm i -D jest-sonar-reporter
          
      - name: NPM Build and test
        run: | 
          npm run build
          npm run test
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'Drop'
          path: '${{ github.workspace }}/build'
